version: '3.8'
services:
  meetups-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"


